export const mockIssues = [
  {
    severity: "WARNING",
    file: "src\\critique\\checkers\\coverage.py",
    line: 3,
    column: 8,
    message: "`os` imported but unused",
    code: "F401",
    reasoning: "Checking against coding standards.",
    code_context: [
      "import subprocess\n",
      "import json\n",
      "import os\n",
      "from typing import List\n",
      "from critique.checkers.base import BaseChecker, Issue, Severity\n",
      "\n",
    ],
    context_start_line: 1,
  },
  {
    severity: "WARNING",
    file: "src\\critique\\checkers\\lint.py",
    line: 38,
    column: 29,
    message: "Local variable `e` is assigned to but never used",
    code: "F841",
    reasoning: "Checking against coding standards.",
    code_context: [
      "                \n",
      "        except json.JSONDecodeError:\n",
      "            pass\n",
      "        except Exception as e:\n",
      "            pass\n",
      "            \n",
      "        return issues\n",
    ],
    context_start_line: 35,
  },
  {
    severity: "WARNING",
    file: "src\\critique\\cli.py",
    line: 3,
    column: 31,
    message: "`typing_extensions.Annotated` imported but unused",
    code: "F401",
    reasoning: "Checking against coding standards.",
    code_context: [
      "import typer\n",
      "from typing import Optional\n",
      "from typing_extensions import Annotated\n",
      "from critique.runner import run_all_checks\n",
      "from critique.git_utils import install_pre_push_hook\n",
      "\n",
    ],
    context_start_line: 1,
  },
  {
    severity: "WARNING",
    file: "src\\critique\\checkers\\coverage.py",
    line: 1,
    column: 0,
    message:
      "Consider possible security implications associated with the subprocess module.",
    code: "B404",
    reasoning: "Security risk detected (LOW).",
    code_context: [
      "import subprocess\n",
      "import json\n",
      "import os\n",
      "from typing import List\n",
    ],
    context_start_line: 1,
  },
  {
    severity: "WARNING",
    file: "src\\critique\\checkers\\coverage.py",
    line: 19,
    column: 0,
    message: "subprocess call - check for execution of untrusted input.",
    code: "B603",
    reasoning: "Security risk detected (LOW).",
    code_context: [
      "        try:\n",
      "            \n",
      '            cmd = ["coverage", "json", "-o", "-"] \n',
      "            result = subprocess.run(cmd, capture_output=True, text=True)\n",
      "            \n",
      "            if result.returncode != 0:\n",
      "                return [Issue(\n",
    ],
    context_start_line: 16,
  },
  {
    severity: "WARNING",
    file: "src\\critique\\checkers\\coverage.py",
    line: 47,
    column: 0,
    message: "Try, Except, Pass detected.",
    code: "B110",
    reasoning: "Security risk detected (LOW).",
    code_context: [
      '                    reasoning="Ensure code is well-tested."\n',
      "                ))\n",
      "                \n",
      "        except Exception:\n",
      "            pass\n",
      "            \n",
      "        return issues\n",
    ],
    context_start_line: 44,
  },
  {
    severity: "WARNING",
    file: "src\\critique\\checkers\\lint.py",
    line: 1,
    column: 0,
    message:
      "Consider possible security implications associated with the subprocess module.",
    code: "B404",
    reasoning: "Security risk detected (LOW).",
    code_context: [
      "import subprocess\n",
      "import json\n",
      "from typing import List\n",
      "from critique.checkers.base import BaseChecker, Issue, Severity\n",
    ],
    context_start_line: 1,
  },
  {
    severity: "WARNING",
    file: "src\\critique\\checkers\\lint.py",
    line: 17,
    column: 0,
    message: "subprocess call - check for execution of untrusted input.",
    code: "B603",
    reasoning: "Security risk detected (LOW).",
    code_context: [
      "        issues = []\n",
      "        try:\n",
      '            cmd = ["ruff", "check", "--output-format=json"] + files\n',
      "            result = subprocess.run(cmd, capture_output=True, text=True)            \n",
      "            data = json.loads(result.stdout)\n",
      "            \n",
      "            for item in data:\n",
    ],
    context_start_line: 14,
  },
  {
    severity: "WARNING",
    file: "src\\critique\\checkers\\lint.py",
    line: 38,
    column: 0,
    message: "Try, Except, Pass detected.",
    code: "B110",
    reasoning: "Security risk detected (LOW).",
    code_context: [
      "                \n",
      "        except json.JSONDecodeError:\n",
      "            pass\n",
      "        except Exception as e:\n",
      "            pass\n",
      "            \n",
      "        return issues\n",
    ],
    context_start_line: 35,
  },
  {
    severity: "WARNING",
    file: "src\\critique\\checkers\\security.py",
    line: 1,
    column: 0,
    message:
      "Consider possible security implications associated with the subprocess module.",
    code: "B404",
    reasoning: "Security risk detected (LOW).",
    code_context: [
      "import subprocess\n",
      "import json\n",
      "from typing import List\n",
      "from critique.checkers.base import BaseChecker, Issue, Severity\n",
    ],
    context_start_line: 1,
  },
  {
    severity: "WARNING",
    file: "src\\critique\\checkers\\security.py",
    line: 17,
    column: 0,
    message: "subprocess call - check for execution of untrusted input.",
    code: "B603",
    reasoning: "Security risk detected (LOW).",
    code_context: [
      "        issues = []\n",
      "        try:\n",
      '            cmd = ["bandit", "-f", "json", "-q"] + files\n',
      "            result = subprocess.run(cmd, capture_output=True, text=True)\n",
      "            \n",
      "            output = result.stdout\n",
      "            if not output.strip():\n",
    ],
    context_start_line: 14,
  },
  {
    severity: "WARNING",
    file: "src\\critique\\checkers\\security.py",
    line: 45,
    column: 0,
    message: "Try, Except, Pass detected.",
    code: "B110",
    reasoning: "Security risk detected (LOW).",
    code_context: [
      '                    reasoning=f"Security risk detected ({sev_str})."\n',
      "                ))\n",
      "                \n",
      "        except Exception:\n",
      "            pass\n",
      "        return issues\n",
    ],
    context_start_line: 42,
  },
  {
    severity: "WARNING",
    file: "src\\critique\\checkers\\types.py",
    line: 1,
    column: 0,
    message:
      "Consider possible security implications associated with the subprocess module.",
    code: "B404",
    reasoning: "Security risk detected (LOW).",
    code_context: [
      "import subprocess\n",
      "import re\n",
      "from typing import List\n",
      "from critique.checkers.base import BaseChecker, Issue, Severity\n",
    ],
    context_start_line: 1,
  },
  {
    severity: "WARNING",
    file: "src\\critique\\checkers\\types.py",
    line: 17,
    column: 0,
    message: "subprocess call - check for execution of untrusted input.",
    code: "B603",
    reasoning: "Security risk detected (LOW).",
    code_context: [
      "        issues = []\n",
      "        try:\n",
      '            cmd = ["mypy", "--show-column-numbers", "--no-error-summary"] + files\n',
      "            result = subprocess.run(cmd, capture_output=True, text=True)\n",
      "            \n",
      "            # Output format: file:line:col: error: message\n",
      "            # e.g. main.py:10:5: error: Incompatible types...\n",
    ],
    context_start_line: 14,
  },
  {
    severity: "WARNING",
    file: "src\\critique\\checkers\\types.py",
    line: 40,
    column: 0,
    message: "Try, Except, Pass detected.",
    code: "B110",
    reasoning: "Security risk detected (LOW).",
    code_context: [
      '                        reasoning="Type mismatch found."\n',
      "                    ))\n",
      "                    \n",
      "        except Exception:\n",
      "            pass\n",
      "            \n",
      "        return issues\n",
    ],
    context_start_line: 37,
  },
  {
    severity: "WARNING",
    file: "src\\critique\\git_utils.py",
    line: 3,
    column: 0,
    message:
      "Consider possible security implications associated with the subprocess module.",
    code: "B404",
    reasoning: "Security risk detected (LOW).",
    code_context: [
      "import os\n",
      "import stat\n",
      "import subprocess\n",
      "import sys\n",
      "from pathlib import Path\n",
      "from rich import print\n",
    ],
    context_start_line: 1,
  },
  {
    severity: "WARNING",
    file: "src\\critique\\git_utils.py",
    line: 12,
    column: 0,
    message: "subprocess call - check for execution of untrusted input.",
    code: "B603",
    reasoning: "Security risk detected (LOW).",
    code_context: [
      'def get_changed_files(target_branch: str = "origin/main") -> List[str]:\n',
      "    try:\n",
      '        cmd = ["git", "diff", "--name-only", "--diff-filter=ACM", f"{target_branch}...HEAD"]\n',
      "        result = subprocess.run(cmd, capture_output=True, text=True, check=True)\n",
      "        files = result.stdout.strip().splitlines()\n",
      '        abs_files = [os.path.abspath(f) for f in files if f.endswith(".py")]\n',
      "        return [f for f in abs_files if os.path.exists(f)]\n",
    ],
    context_start_line: 9,
  },
  {
    severity: "WARNING",
    file: "src\\critique\\report.py",
    line: 60,
    column: 0,
    message: "Try, Except, Pass detected.",
    code: "B110",
    reasoning: "Security risk detected (LOW).",
    code_context: [
      "    \n",
      "    try:\n",
      '        webbrowser.open(f"file://{os.path.abspath(report_path)}")\n',
      "    except Exception:\n",
      "        pass\n",
      "\n",
      "    if fatal_issues:\n",
    ],
    context_start_line: 57,
  },
  {
    severity: "FATAL",
    file: "src\\critique\\runner.py",
    line: 34,
    column: 72,
    message:
      'Incompatible default for argument "custom_files" (default has type "None", argument has type "list[str]")  [assignment]',
    code: "TYPE",
    reasoning: "Type mismatch found.",
    code_context: [
      "\n",
      "console = Console()\n",
      "\n",
      "def run_all_checks(incremental: bool = True, custom_files: List[str] = None) -> bool:\n",
      '    """\n',
      "    Orchestrates the execution of all enabled checkers.\n",
      "    Returns True if execution flows allow a push (Pass or Warnings only), False if Fatal.\n",
    ],
    context_start_line: 31,
  },
  {
    severity: "FATAL",
    file: "src\\critique\\cli.py",
    line: 18,
    column: 68,
    message:
      'Argument "custom_files" to "run_all_checks" has incompatible type "list[str] | None"; expected "list[str]"  [arg-type]',
    code: "TYPE",
    reasoning: "Type mismatch found.",
    code_context: [
      '    """\n',
      "    Run all configured checks (Lint, Types, Security, Tests).\n",
      '    """\n',
      "    success = run_all_checks(incremental=incremental, custom_files=files)\n",
      "    if not success:\n",
      '        typer.echo("Checks failed. Fix the issues or use --no-verify to bypass (not recommended).")\n',
      "        raise typer.Exit(code=1)\n",
    ],
    context_start_line: 15,
  },
  {
    severity: "INFO",
    file: "PROJECT",
    line: 0,
    column: 0,
    message: "No coverage data found. Run tests with coverage first.",
    code: "COV001",
    reasoning: "Coverage check requires .coverage data.",
    code_context: [],
    context_start_line: 1,
  },
];
