"""
Natural-language assistant for the CodeCritique CLI.

Two entry points, both backed by the same provider-agnostic LLMClient the
review pipeline uses:

- `ask`: answers questions about what the tool can do.  The model is grounded
  in a manifest generated by introspecting the real Typer app, so the answers
  never drift from the actual commands.

- `do`: translates a plain-English instruction into a plan of whitelisted
  actions.  The model can only choose from ACTIONS below — it never emits
  shell commands or arbitrary code — and the plan is shown to the user for
  confirmation before anything runs.
"""

import json
from typing import Any, Callable, Dict, List, Optional, Tuple

from rich.console import Console

from critique.ai.client import LLMClient

console = Console(stderr=True)


# ---------------------------------------------------------------------------
# Capability manifest (for `ask`) — generated from the real CLI
# ---------------------------------------------------------------------------

def build_manifest() -> str:
    """Describe every CLI command by introspecting the Typer app.

    Imported lazily to avoid a circular import (cli.py imports this module).
    """
    import click
    import typer.main

    from critique.cli import app

    root = typer.main.get_command(app)
    lines: List[str] = []

    def describe(cmd: "click.Command", prefix: str) -> None:
        help_text = (cmd.help or cmd.short_help or "").strip().split("\n\n")[0]
        help_text = " ".join(help_text.split())
        params = []
        for p in cmd.params:
            if isinstance(p, click.Option):
                params.append("/".join(p.opts))
            elif isinstance(p, click.Argument):
                params.append(f"<{p.name}>")
        param_str = f" (options: {', '.join(params)})" if params else ""
        lines.append(f"- `codecritique {prefix}{cmd.name}`: {help_text}{param_str}")

    assert isinstance(root, click.Group)
    for name, cmd in sorted(root.commands.items()):
        if isinstance(cmd, click.Group):
            for sub_name, sub in sorted(cmd.commands.items()):
                describe(sub, f"{name} ")
        else:
            describe(cmd, "")

    return "\n".join(lines)


ASK_SYSTEM = """\
You are the CodeCritique assistant, helping a developer use the CodeCritique \
CLI (a local pre-push code review tool for Python and C/C++).

You will be given the tool's full command manifest and a question. Answer \
using ONLY the manifest:
- Be concise and friendly; show exact commands in backticks.
- If the question asks for something the tool cannot do, say so plainly and \
suggest the closest supported alternative if one exists.
- Do not invent commands, options, or behavior that are not in the manifest."""


def answer_question(question: str, llm: LLMClient) -> str:
    user = f"Command manifest:\n{build_manifest()}\n\nQuestion: {question}"
    return llm.complete(ASK_SYSTEM, user, temperature=0.2)


# ---------------------------------------------------------------------------
# Whitelisted actions (for `do`)
# ---------------------------------------------------------------------------

def _do_check(files: Optional[List[str]] = None, incremental: bool = True,
              ai: bool = False) -> bool:
    from critique.runner import run_all_checks
    return run_all_checks(incremental=incremental, custom_files=files, use_ai=ai)


def _do_fix(files: Optional[List[str]] = None, incremental: bool = True,
            unsafe: bool = False) -> bool:
    from critique.runner import fix_files
    return fix_files(incremental=incremental, custom_files=files, unsafe=unsafe)


def _do_format(files: Optional[List[str]] = None, incremental: bool = True,
               in_place: bool = False) -> bool:
    # Pass every parameter explicitly: calling a Typer command function with
    # its defaults would hand us OptionInfo sentinels instead of values.
    from critique.cli import format_code
    format_code(files=files, incremental=incremental, in_place=in_place, backup=True)
    return True


def _do_list_reports() -> bool:
    from critique.cli import list_saved_reports
    list_saved_reports()
    return True


def _do_install_hooks() -> bool:
    from critique.git_utils import install_pre_push_hook
    install_pre_push_hook()
    return True


# Settings `do` may change, with their allowed values (None = free-form, the
# config layer's own coercion/validation applies). API keys are deliberately
# absent: secrets must never travel through an LLM prompt or plan — point the
# user at `codecritique config set-key <provider>` instead.
def _configurable_settings() -> Dict[str, Optional[List[str]]]:
    from critique.config import SUPPORTED_PROVIDERS
    from critique.languages import LANGUAGE_CHOICES
    from critique.profiles import BUILTIN_PROFILES
    return {
        "provider": list(SUPPORTED_PROVIDERS),
        "model": None,
        "base_url": None,
        "temperature": None,
        "timeout": None,
        "language": list(LANGUAGE_CHOICES),
        "suggestion_mode": list(BUILTIN_PROFILES),
        "project_context": None,
        "custom_instructions": None,
        "style_learning": ["on", "off"],
        "adaptive_style": ["on", "off"],
    }


def _do_set_config(setting: str = "", value: str = "") -> bool:
    allowed = _configurable_settings()
    setting = str(setting).strip().lower()

    if "key" in setting:
        console.print(
            "[yellow]API keys can't be set through the assistant — run "
            "`codecritique config set-key <provider>` yourself (input is hidden).[/yellow]"
        )
        return False
    if setting not in allowed:
        console.print(
            f"[red]Unknown setting {setting!r}. "
            f"Configurable: {', '.join(sorted(allowed))}.[/red]"
        )
        return False

    choices = allowed[setting]
    normalized = str(value).strip()
    if choices is not None and normalized.lower() not in choices:
        console.print(
            f"[red]Invalid value {value!r} for {setting}. "
            f"Choose one of: {', '.join(choices)}.[/red]"
        )
        return False

    from critique.config import set_value
    try:
        set_value(setting, normalized)
    except (ValueError, TypeError) as exc:
        console.print(f"[red]Could not set {setting}: {exc}[/red]")
        return False
    console.print(f"[green]Set {setting} = {normalized}[/green]")
    return True


# action name -> (handler, description, {arg: description})
ACTIONS: Dict[str, Tuple[Callable[..., bool], str, Dict[str, str]]] = {
    "check": (
        _do_check,
        "Run the static analysis checks (and optionally the AI review).",
        {
            "files": "list of file paths to check; omit for changed files",
            "incremental": "bool; false = scan the whole repo (default true)",
            "ai": "bool; true = include the slower AI review (default false)",
        },
    ),
    "fix": (
        _do_fix,
        "Apply ruff's safe lint fixes and reformat files in place.",
        {
            "files": "list of file paths to fix; omit for changed files",
            "incremental": "bool; false = fix the whole repo (default true)",
            "unsafe": "bool; true = also apply behavior-changing fixes (default false)",
        },
    ),
    "format": (
        _do_format,
        "AI-restyle code for review (preview a diff, or write with in_place).",
        {
            "files": "list of file paths; omit for changed files",
            "incremental": "bool (default true)",
            "in_place": "bool; true = write changes to disk (default false: preview only)",
        },
    ),
    "list_reports": (
        _do_list_reports,
        "Show recently saved review reports.",
        {},
    ),
    "install_hooks": (
        _do_install_hooks,
        "Install the git pre-push hook in the current repository.",
        {},
    ),
    "set_config": (
        _do_set_config,
        "Change a persistent CodeCritique setting (never API keys).",
        {
            "setting": "string; the setting name (see 'settings' below)",
            "value": "string; the new value",
        },
    ),
}

# Action args treated as strings during plan validation (everything else is
# a boolean, except the special-cased "files" list).
_STRING_ARGS = {"setting", "value"}


def _actions_for_prompt() -> str:
    spec: Dict[str, Any] = {
        name: {"description": desc, "args": args}
        for name, (_, desc, args) in ACTIONS.items()
    }
    spec["set_config"]["settings"] = {
        name: (choices if choices is not None else "free-form")
        for name, choices in _configurable_settings().items()
    }
    return json.dumps(spec, indent=2)


DO_SCHEMA: Dict[str, Any] = {
    "type": "object",
    "properties": {
        "reply": {"type": "string"},
        "plan": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "action": {"type": "string"},
                    "args": {"type": "object"},
                },
                "required": ["action"],
            },
        },
    },
    "required": ["reply", "plan"],
}


def _do_system() -> str:
    return f"""\
You translate a developer's plain-English request into a plan of CodeCritique \
actions. You may ONLY use the actions and arguments listed below — never \
invent actions, never emit shell commands.

Available actions:
{_actions_for_prompt()}

Rules:
- Keep plans minimal: only the steps the request actually asks for.
- Order matters; steps run sequentially and stop on the first failure.
- If the request cannot be satisfied with these actions, return an empty \
plan and explain why in "reply".
- "reply" is a one-or-two-sentence note to the developer about what the plan \
does (or why there is no plan).

Return ONLY a JSON object in this EXACT format:
{{
  "reply": "<short note to the developer>",
  "plan": [
    {{"action": "<action name>", "args": {{...}}}}
  ]
}}"""


# ---------------------------------------------------------------------------
# Plan validation + execution
# ---------------------------------------------------------------------------

def validate_plan(raw: Any) -> Tuple[List[Dict[str, Any]], List[str]]:
    """Check a model-produced plan against the action whitelist.

    Returns (steps, errors). Unknown actions are errors; unknown or
    mistyped args are dropped with a warning entry so a sloppy model
    response degrades instead of executing something unintended.
    """
    steps: List[Dict[str, Any]] = []
    errors: List[str] = []

    plan = raw.get("plan", []) if isinstance(raw, dict) else []
    if not isinstance(plan, list):
        return [], ["Model returned a malformed plan."]

    for i, step in enumerate(plan):
        if not isinstance(step, dict):
            errors.append(f"Step {i + 1} is malformed.")
            continue
        action = step.get("action")
        if action not in ACTIONS:
            errors.append(f"Step {i + 1} uses unknown action {action!r}.")
            continue

        _, _, allowed = ACTIONS[action]
        args_in = step.get("args") or {}
        args: Dict[str, Any] = {}
        if isinstance(args_in, dict):
            for key, value in args_in.items():
                if key not in allowed:
                    errors.append(
                        f"Step {i + 1} ({action}): dropped unknown argument {key!r}."
                    )
                    continue
                if key == "files":
                    if isinstance(value, str):
                        value = [value]
                    if not (isinstance(value, list)
                            and all(isinstance(f, str) for f in value)):
                        errors.append(
                            f"Step {i + 1} ({action}): dropped invalid 'files' value."
                        )
                        continue
                elif key in _STRING_ARGS:
                    if isinstance(value, (str, int, float, bool)):
                        value = str(value)
                    else:
                        errors.append(
                            f"Step {i + 1} ({action}): dropped non-scalar {key!r}."
                        )
                        continue
                elif not isinstance(value, bool):
                    errors.append(
                        f"Step {i + 1} ({action}): dropped non-boolean {key!r}."
                    )
                    continue
                args[key] = value
        steps.append({"action": action, "args": args})

    return steps, errors


def describe_plan(steps: List[Dict[str, Any]]) -> List[str]:
    """Human-readable one-liners for the confirmation prompt."""
    lines = []
    for i, step in enumerate(steps, start=1):
        _, desc, _ = ACTIONS[step["action"]]
        arg_str = ", ".join(f"{k}={v!r}" for k, v in step["args"].items())
        suffix = f" ({arg_str})" if arg_str else ""
        # ASCII separator: keeps Windows cp1252 consoles happy.
        lines.append(f"{i}. {step['action']}{suffix} - {desc}")
    return lines


def plan_actions(instruction: str, llm: LLMClient) -> Dict[str, Any]:
    """Ask the model for a plan. Returns the raw response dict."""
    result = llm.complete_json(
        system=_do_system(),
        user=f"Request: {instruction}",
        schema=DO_SCHEMA,
    )
    return result if isinstance(result, dict) else {"reply": "", "plan": []}


def run_plan(steps: List[Dict[str, Any]]) -> bool:
    """Execute validated steps in order; stop on the first failure."""
    for i, step in enumerate(steps, start=1):
        handler, _, _ = ACTIONS[step["action"]]
        console.print(f"[bold blue]Step {i}/{len(steps)}: {step['action']}[/bold blue]")
        try:
            ok = handler(**step["args"])
        except Exception as exc:
            console.print(f"[red]Step {i} ({step['action']}) failed: {exc}[/red]")
            return False
        if ok is False:
            console.print(
                f"[red]Step {i} ({step['action']}) reported failure — stopping.[/red]"
            )
            return False
    return True
