"""
Config system for CodeCritique.

Loads ~/.codecritique/config.toml using tomllib (Python 3.11+).
Falls back to sensible defaults when no config file exists.
"""

from __future__ import annotations

import os
import sys
from dataclasses import dataclass, field
from pathlib import Path
from typing import Dict, List, Optional

CONFIG_DIR = Path.home() / ".codecritique"
CONFIG_PATH = CONFIG_DIR / "config.toml"

STARTER_CONFIG = """\
# CodeCritique configuration
# Generated by: critique init-config
# Edit to customize behavior.

# LLM provider: "ollama" | "anthropic" | "openai"
provider = "ollama"

# Model name (provider-specific)
# Ollama examples:  "qwen2.5-coder:7b", "codellama:13b"
# Anthropic examples: "claude-haiku-4-5-20251001", "claude-sonnet-4-6"
# OpenAI examples: "gpt-4o-mini", "gpt-4o"
model = "qwen2.5-coder:7b"

[ollama]
base_url = "http://localhost:11434"

# Map issue code → severity override ("FATAL" | "WARNING" | "INFO")
# Example: make a specific ruff rule fatal
# [severity_overrides]
# E501 = "INFO"

# Checkers to disable. Valid names: "ruff", "bandit", "mypy", "coverage", "ai-critic"
# skip_checkers = []

# Maximum file size (chars) to send to AI. Files larger than this are skipped.
max_file_chars = 30000
"""


@dataclass
class OllamaConfig:
    base_url: str = "http://localhost:11434"


@dataclass
class Config:
    provider: str = "ollama"
    model: str = "qwen2.5-coder:7b"
    ollama: OllamaConfig = field(default_factory=OllamaConfig)
    severity_overrides: Dict[str, str] = field(default_factory=dict)
    skip_checkers: List[str] = field(default_factory=list)
    max_file_chars: int = 30_000


def _load_toml(path: Path) -> dict:
    """Load a TOML file using the stdlib tomllib (3.11+) or tomli fallback."""
    if sys.version_info >= (3, 11):
        import tomllib
        with open(path, "rb") as f:
            return tomllib.load(f)
    else:
        try:
            import tomli  # type: ignore[import]
            with open(path, "rb") as f:
                return tomli.load(f)
        except ImportError:
            raise RuntimeError(
                "Python < 3.11 requires the 'tomli' package: pip install tomli"
            )


def load_config() -> Config:
    """
    Load and return the active Config.

    Reads ~/.codecritique/config.toml when present, otherwise returns defaults.
    Environment variables CRITIQUE_PROVIDER / CRITIQUE_MODEL override the file.
    """
    cfg = Config()

    if CONFIG_PATH.exists():
        try:
            data = _load_toml(CONFIG_PATH)
        except Exception:
            data = {}

        cfg.provider = data.get("provider", cfg.provider)
        cfg.model = data.get("model", cfg.model)
        cfg.max_file_chars = int(data.get("max_file_chars", cfg.max_file_chars))
        cfg.skip_checkers = list(data.get("skip_checkers", []))
        cfg.severity_overrides = dict(data.get("severity_overrides", {}))

        ollama_section = data.get("ollama", {})
        cfg.ollama = OllamaConfig(
            base_url=ollama_section.get("base_url", cfg.ollama.base_url)
        )

    # Environment variable overrides (always win)
    env_provider = os.environ.get("CRITIQUE_PROVIDER")
    if env_provider:
        cfg.provider = env_provider

    env_model = os.environ.get("CRITIQUE_MODEL")
    if env_model:
        cfg.model = env_model

    return cfg


def write_starter_config() -> None:
    """Write the starter config.toml to ~/.codecritique/config.toml."""
    CONFIG_DIR.mkdir(parents=True, exist_ok=True)
    CONFIG_PATH.write_text(STARTER_CONFIG, encoding="utf-8")
